name: CI/Deno Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.3.3

      - name: Format code
        run: deno fmt

      - name: Run unit tests
        env:
          ENVIRONMENT: development
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: deno task test --no-check
