name: Build docker image

on:
    workflow_run:
        workflows: ["CI/Deno Test"]
        types: ["completed"]
        branches:
          - homolog

jobs:
    build-push-ghcr:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image to GHCR
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/poligrades/poligrades-backend:latest